dist: trusty
sudo: required
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'   # Change to "3.7" once Travis gets it on their machines
before_script:
- make ci-setup
script:
- make proto
- make test

# Only email on failure
notifications:
  email:
    on_success: never
    on_failure: always
