dist: trusty
sudo: required
language: python
python:
  - 2.7
  - 3.5
before_script:
- make ci-setup
script:
- make test

# Only email on failure
notifications:
  email:
    on_success: never
    on_failure: always
